[package]
name = "remote_ldr"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.5"
tonic = "0.12.3"
tokio = { version = "1.43", features = ["macros", "rt-multi-thread"] }
gethostname = "1.0.0"

[build-dependencies]
tonic-build = "0.12.3"

